namespace ProperAppUpdater.Services;

public sealed class LocalizationService
{
    private static readonly IReadOnlyDictionary<string, string> Turkish = new Dictionary<string, string>
    {
        ["AppName"] = "Süpürücü",
        ["DeckSwitcher"] = "Sonraki çalışma alanına kaydır",
        ["DeckNextPage"] = "Sonraki sayfa: {0}",
        ["DeckUpdate"] = "Güncelle",
        ["DeckDelete"] = "Sil",
        ["DeckPatch"] = "Yama",
        ["DeckBackup"] = "Yedekle",
        ["DeckInDevelopment"] = "Geliştirme aşamasında",
        ["DeckPlanned"] = "PLANLANAN ÖZELLİKLER",
        ["DeckPreviewFooter"] = "Bu alan geliştirme aşamasında. İşlem düğmeleri henüz etkin değil.",
        ["DeckDeleteTitle"] = "Uygulamalar ve büyük dosyalar",
        ["DeckDeleteDescription"] = "Bu alan hâlâ geliştiriliyor. Kurulu uygulamaları inceleyip en çok yer kaplayan dosyaları bulmana yardımcı olacak.",
        ["DeckDeleteFeatures"] = "• Seçtiğin uygulamaları kaldır\n• En büyük dosyaları ve konumlarını gör\n• Temizlemeden önce ne silineceğini incele",
        ["DeckDeleteFind"] = "Uygulamaları incele",
        ["DeckDeleteAction"] = "Büyük dosyalar",
        ["DeckPatchTitle"] = "Windows’u kendine göre düzenle",
        ["DeckPatchDescription"] = "Bu alan hâlâ geliştiriliyor. Copilot ve Edge gibi istemediğin Windows uygulamalarını bulup seçeneklerini incelemeni sağlayacak.",
        ["DeckPatchFeatures"] = "• Windows uygulamalarını gözden geçir\n• Hangilerini istemediğine kendin karar ver\n• Değişiklikten önce planı incele",
        ["DeckPatchFind"] = "Windows’u incele",
        ["DeckPatchAction"] = "Yama planı",
        ["DeckBackupTitle"] = "Windows’unu yanında götür",
        ["DeckBackupDescription"] = "Bu alan hâlâ geliştiriliyor. Büyük hedef: Windows düzenini kopyalayıp Linux veya macOS üzerinde çalıştırmanın yollarını araştırmak.",
        ["DeckBackupFeatures"] = "• Windows’u ve kişisel düzenini kopyala\n• Geri yükleme ve kurtarmayı planla\n• Linux / macOS’a taşınabilirliği araştır",
        ["DeckBackupFind"] = "Yedekleme planı",
        ["DeckBackupAction"] = "Taşınabilirliği keşfet",
        ["SetupQuestion"] = "Which language / Hangi dili kullanıyorsun?",
        ["SetupSubtitle"] = "Bu seçim uygulama adını ve tüm metinleri belirler.",
        ["ReadyStatus"] = "Süpürmeye hazır!",
        ["LaunchFinished"] = "Açılış tamam.",
        ["FindOldButton"] = "Morukları bul",
        ["SweepButton"] = "Süpür!",
        ["PirateButton"] = "Korsan-aslanı!",
        ["ReadyFooter"] = "Açık uygulamaları kapatmadan önce sorar. Seçtiğin uygulamaları günceller.",
        ["OldSearching"] = "Güncellemeler aranıyor...",
        ["UpdaterSweepStatus"] = "Güncelleme araçları hazırlanıyor",
        ["UpdaterSweepFooter"] = "WinGet, Chocolatey ve Scoop kendini toparlıyor.",
        ["UpdaterFreshStatus"] = "Güncelleme araçları hazır.",
        ["InstalledAppsChecking"] = "Kurulu uygulamalar kontrol ediliyor.",
        ["CheckingApp"] = "{0} kontrol ediliyor.",
        ["PackageManagersChecking"] = "WinGet/Chocolatey/Scoop kontrol ediliyor.",
        ["CleanNoOld"] = "Güncellemeler tamam. Eski uygulama yok.",
        ["OldAppsFound"] = "{0} uygulama güncellenebilir.",
        ["ScanFooterOk"] = "{0} katalog uygulaması, {1} paket uygulaması kontrol edildi. {2} katalog boşluğu raporlandı.",
        ["ScanFooterErrors"] = "{0} katalog uygulaması, {1} paket uygulaması kontrol edildi, {2} kaynak hatası. {3} katalog boşluğu raporlandı.",
        ["ScanFooterBlocked"] = "{0} inatçı güncelleme saklandı.",
        ["CheckCrashed"] = "Kontrol başarısız oldu.",
        ["NoSelection"] = "Süpürülecek bir şey yok.",
        ["Sweeping"] = "Süpürülüyor...",
        ["Updated"] = "{0} güncellendi.",
        ["Done"] = "Bitti.",
        ["DoneWithIssues"] = "Bitti, ama her şey değil.",
        ["SweepSummary"] = "{0} güncellendi, {1} başarısız, {2} atlandı, {3} güven uyarısı.",
        ["SweepSummaryShortcuts"] = "{0} yeni masaüstü kısayolu kaldırıldı.",
        ["AssistantDoneWithIssues"] = "Bazıları kaldı.",
        ["VerifyingInstalled"] = "Sonuç doğrulanıyor",
        ["UpdateStillPending"] = "Paket yöneticisi başarılı dedi ama güncelleme hâlâ bekliyor.",
        ["DesktopCleanupDone"] = "Süpürme bitti.",
        ["LocalCleanupDone"] = "{0} eski Süpürücü indirmesi temizlendi.",
        ["RecoverableError"] = "Hata yakalandı.",
        ["Error"] = "Hata",
        ["OldStatus"] = "Güncelleme var",
        ["CurrentStatus"] = "Güncel",
        ["Downloading"] = "İndiriliyor",
        ["DownloadingPercent"] = "İndiriliyor ({0}%)",
        ["DownloadingLimitedPercent"] = "İndiriliyor ({0}%, küçükler öncelikli)",
        ["DownloadTimedOut"] = "İndirme zaman aşımına uğradı ve durduruldu.",
        ["Verifying"] = "Doğrulanıyor",
        ["Installing"] = "Kuruluyor",
        ["StillInstalling"] = "Kurulum devam ediyor...",
        ["InstallerTimedOut"] = "Kurulum takıldı ve durduruldu.",
        ["PackageManager"] = "Paket yöneticisi",
        ["UpdaterWingetSource"] = "WinGet kaynakları yenileniyor.",
        ["UpdaterWingetCheck"] = "WinGet kendini kontrol ediyor.",
        ["UpdaterWingetUpdate"] = "WinGet güncelleniyor.",
        ["UpdaterChocoCheck"] = "Chocolatey kendini kontrol ediyor.",
        ["UpdaterChocoUpdate"] = "Chocolatey güncelleniyor.",
        ["UpdaterScoopUpdate"] = "Scoop ve bucket'lar yenileniyor.",
        ["UpdaterSummaryClean"] = "WinGet, Chocolatey ve Scoop temiz.",
        ["UpdaterSummarySkipped"] = "Gerekli araç eksik: {0}.",
        ["UpdaterSummaryErrors"] = "Güncelleyici bakımı bitti. {0} hata, {1} atlandı.",
        ["ToolMissing"] = "{0} bulunamadı.",
        ["PirateTitle"] = "Korsan-aslanı!",
        ["PirateIntro"] = "Süpürücü'nün dokunmaması gereken uygulamaları seç.",
        ["DoNotSweep"] = "Listeyi kaydet",
        ["Close"] = "Kapat",
        ["IgnoredSaved"] = "Korsan-aslanı kaydedildi: {0} uygulama.",
        ["IgnoredNothing"] = "Seçili uygulama yok.",
        ["AllAppsLoading"] = "Uygulamalar yükleniyor...",
        ["SelfNeedsSweep"] = "Süpürülmeliyim:/",
        ["AssistantWorking"] = "Süpürüyorum...",
        ["AssistantDone"] = "Bitti.",
        ["AssistantTargetCaption"] = "Süpürülüyor",
        ["AssistantBlockedCry"] = "başaramadık abi",
        ["AssistantSizeSmall"] = "Küçük",
        ["AssistantSizeMedium"] = "Orta",
        ["AssistantSizeLarge"] = "Büyük",
        ["PirateCandidateMenu"] = "Korsanbu!",
        ["DeleteCandidateMenu"] = "Kaldır…",
        ["FilePathCandidateMenu"] = "Dosyada Aç",
        ["IgnoredCandidateStatus"] = "{0}, Korsan-aslanı listesine eklendi.",
        ["SystemUninstallerOpened"] = "Sistem kaldırma ekranı açıldı.",
        ["FilePathMissing"] = "Dosya yolu bulunamadı.",
        ["AppOpenStatus"] = "{0} açık. Güncelleme atlandı.",
        ["AppOpenFooter"] = "Önce {0} kapatılmalı.",
        ["FailureAttemptStatus"] = "Olmadı {0}/{1}",
        ["BlockedStatus"] = "Bloklandı",
        ["BlockedAfterFailuresFooter"] = "{0} üç kez olmadı. Şimdilik bloklandı.",
        ["UpdatedUnverified"] = "{0} güncellendi. Uyarı: {1}",
        ["TrustUnsigned"] = "yükleyici imzasız",
        ["TrustInvalidSig"] = "imza doğrulanamadı",
        ["TrustPublisherMismatch"] = "imza sahibi '{0}', beklenen '{1}' değil",
        ["ChecksumMismatch"] = "{0} sağlaması tutmadı; indirme bozuk olabilir",
        ["InstallerTooLarge"] = "Yükleyici beklenenden çok büyük; durduruldu",
        ["UnsafeDownloadPath"] = "İndirme yolu Süpürücü klasörünün dışına çıktı; durduruldu",
        ["AppOpenAskClose"] = "{0} arka planda açık olduğu için güncelleyemiyorum. Kapatmamı ister misin?",
        ["ClosingApp"] = "{0} kapatılıyor...",
        ["AppCloseFailed"] = "{0} kapatılamadı; güncelleme atlandı.",
        ["DesktopShortcutsCleaned"] = "Süpürme bitti. {0} yeni masaüstü kısayolu kaldırıldı.",
        ["ResetBlocksMenu"] = "Engellenenleri sıfırla",
        ["BlocksReset"] = "{0} engel sıfırlandı.",
        ["SetupPreparing"] = "Bilgisayarın hazırlanıyor",
        ["SetupPrepareExplanation"] = "Gerekli araçlar kurulup yenilenir. Süpürücü ardından açılır.",
        ["SetupPreparingFolders"] = "Yerel klasörler ve yazma erişimi kontrol ediliyor...",
        ["SetupReady"] = "Süpürmeye hazır!",
        ["SetupNoTools"] = "Gerekli araçlar eksik.",
        ["SetupToolsFound"] = "Kurulu araçlar: {0}",
        ["LanguageMenu"] = "Language",
        ["Minimize"] = "Simge durumuna küçült",
        ["DownloadReady"] = "İndirildi; kurulum bekliyor",
        ["DownloadQueued"] = "İndirme sırasında",
        ["UsingVerifiedDownload"] = "Doğrulanmış indirme kullanılıyor",
        ["DownloadIncomplete"] = "İndirme eksik; yükleyici çalıştırılmadı.",
        ["SetupCheckingTool"] = "{0} kontrol ediliyor...",
        ["SetupInstallingTool"] = "{0} kuruluyor...",
        ["SetupToolFailed"] = "{0} hazırlanamadı. Yeniden dene.",
        ["SetupStillPreparing"] = "Araç kurulumu devam ediyor...",
        ["SetupToolError"] = "Araç kurulumu başarısız oldu.",
        ["SetupNeedsRepair"] = "Hazırlık tamamlanamadı",
        ["SetupRetry"] = "Yeniden dene",
        ["UnsafeLinkedPath"] = "Bağlantı içeren veri yolu reddedildi.",
        ["SelfSweepButton"] = "Süpürücü’yü süpür",
        ["DeleteSelfButton"] = "Süpürücü’yü sil",
        ["SelfChecking"] = "Süpürücü kontrol ediliyor...",
        ["SelfCurrent"] = "Süpürücü güncel!",
        ["SelfUnverified"] = "Yeni Süpürücü sürümünün sağlaması doğrulanamadı.",
        ["SelfPortableOnly"] = "Bu işlem taşınabilir EXE derlemesinde kullanılabilir.",
        ["SelfRestarting"] = "Süpürücü güncellenip yeniden açılıyor...",
        ["DeleteSelfConfirm"] = "Süpürücü’nün bu kopyası silinsin mi? Uygulama kapanır ve yalnızca {0} kaldırılır."
    };

    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["AppName"] = "Sweepable’r",
        ["DeckSwitcher"] = "Swipe to the next workspace",
        ["DeckNextPage"] = "Next page: {0}",
        ["DeckUpdate"] = "Update",
        ["DeckDelete"] = "Delete",
        ["DeckPatch"] = "Patch",
        ["DeckBackup"] = "Backup",
        ["DeckInDevelopment"] = "In development",
        ["DeckPlanned"] = "PLANNED FEATURES",
        ["DeckPreviewFooter"] = "This deck is in development. Its action buttons are not active yet.",
        ["DeckDeleteTitle"] = "Apps & large files",
        ["DeckDeleteDescription"] = "This deck is still in development. It will help you review installed apps and find the files taking up the most space.",
        ["DeckDeleteFeatures"] = "• Remove the apps you choose\n• See your largest files and their locations\n• Review what will be deleted before cleanup",
        ["DeckDeleteFind"] = "Review apps",
        ["DeckDeleteAction"] = "Largest files",
        ["DeckPatchTitle"] = "Make Windows your own",
        ["DeckPatchDescription"] = "This deck is still in development. It will find unwanted Windows apps, such as Copilot and Edge, for you to review.",
        ["DeckPatchFeatures"] = "• Review built-in Windows apps\n• Choose which ones you do not want\n• Inspect the plan before changing anything",
        ["DeckPatchFind"] = "Review Windows",
        ["DeckPatchAction"] = "Patch plan",
        ["DeckBackupTitle"] = "Take your Windows with you",
        ["DeckBackupDescription"] = "This deck is still in development. The long-term goal is to copy your Windows setup and explore ways to run it on Linux or macOS.",
        ["DeckBackupFeatures"] = "• Copy Windows and your personal setup\n• Plan restore and recovery\n• Explore Linux / macOS portability",
        ["DeckBackupFind"] = "Backup plan",
        ["DeckBackupAction"] = "Explore portability",
        ["SetupQuestion"] = "Which language / Hangi dili kullanıyorsun?",
        ["SetupSubtitle"] = "This choice controls the app name and all text.",
        ["ReadyStatus"] = "Ready to Sweep!",
        ["LaunchFinished"] = "Launch finished.",
        ["FindOldButton"] = "Detect geezer's",
        ["SweepButton"] = "Sweep!",
        ["PirateButton"] = "Pirate Lover!",
        ["ReadyFooter"] = "Updates your selection. Asks before closing open apps.",
        ["OldSearching"] = "Finding updates...",
        ["UpdaterSweepStatus"] = "Preparing update tools",
        ["UpdaterSweepFooter"] = "WinGet, Chocolatey, and Scoop are refreshing themselves.",
        ["UpdaterFreshStatus"] = "Update tools are ready.",
        ["InstalledAppsChecking"] = "Checking installed apps.",
        ["CheckingApp"] = "Checking {0}.",
        ["PackageManagersChecking"] = "Checking WinGet/Chocolatey/Scoop.",
        ["CleanNoOld"] = "All checked apps are up to date.",
        ["OldAppsFound"] = "{0} app update(s) available.",
        ["ScanFooterOk"] = "Checked {0} catalog apps and {1} package apps. {2} catalog gaps reported.",
        ["ScanFooterErrors"] = "Checked {0} catalog apps and {1} package apps; {2} source errors. {3} catalog gaps reported.",
        ["ScanFooterBlocked"] = "{0} stubborn update(s) hidden.",
        ["CheckCrashed"] = "Couldn’t finish the check.",
        ["NoSelection"] = "Nothing to sweep.",
        ["Sweeping"] = "Sweeping...",
        ["Updated"] = "{0} updated.",
        ["Done"] = "Done.",
        ["DoneWithIssues"] = "Done, with loose ends.",
        ["SweepSummary"] = "{0} updated, {1} failed, {2} skipped, {3} trust warning(s).",
        ["SweepSummaryShortcuts"] = "Removed {0} new desktop shortcut(s).",
        ["AssistantDoneWithIssues"] = "Some are still here.",
        ["VerifyingInstalled"] = "Verifying result",
        ["UpdateStillPending"] = "The package manager reported success, but the update is still pending.",
        ["DesktopCleanupDone"] = "Sweep finished.",
        ["LocalCleanupDone"] = "Cleared {0} old Sweepable’r download(s).",
        ["RecoverableError"] = "Caught an error.",
        ["Error"] = "Error",
        ["OldStatus"] = "Update available",
        ["CurrentStatus"] = "Current",
        ["Downloading"] = "Downloading",
        ["DownloadingPercent"] = "Downloading ({0}%)",
        ["DownloadingLimitedPercent"] = "Downloading ({0}%, small files first)",
        ["DownloadTimedOut"] = "Download timed out and was stopped.",
        ["Verifying"] = "Verifying",
        ["Installing"] = "Installing",
        ["StillInstalling"] = "Still installing...",
        ["InstallerTimedOut"] = "Installer got stuck and was stopped.",
        ["PackageManager"] = "Package manager",
        ["UpdaterWingetSource"] = "Refreshing WinGet sources.",
        ["UpdaterWingetCheck"] = "Checking WinGet itself.",
        ["UpdaterWingetUpdate"] = "Updating WinGet.",
        ["UpdaterChocoCheck"] = "Checking Chocolatey itself.",
        ["UpdaterChocoUpdate"] = "Updating Chocolatey.",
        ["UpdaterScoopUpdate"] = "Refreshing Scoop and buckets.",
        ["UpdaterSummaryClean"] = "WinGet, Chocolatey, and Scoop are clean.",
        ["UpdaterSummarySkipped"] = "{0} required tool(s) missing.",
        ["UpdaterSummaryErrors"] = "Updater maintenance finished. {0} error(s), {1} skipped.",
        ["ToolMissing"] = "{0} not found.",
        ["PirateTitle"] = "Pirate Lover!",
        ["PirateIntro"] = "Select the apps Pirate Lover should protect from sweeping.",
        ["DoNotSweep"] = "Save list",
        ["Close"] = "Close",
        ["IgnoredSaved"] = "Pirate Lover saved: {0} app(s).",
        ["IgnoredNothing"] = "No apps selected.",
        ["AllAppsLoading"] = "Loading apps...",
        ["SelfNeedsSweep"] = "I need a Sweep :/",
        ["AssistantWorking"] = "Sweeping...",
        ["AssistantDone"] = "Done.",
        ["AssistantTargetCaption"] = "Updating",
        ["AssistantBlockedCry"] = "This one beat us.",
        ["AssistantSizeSmall"] = "Small",
        ["AssistantSizeMedium"] = "Medium",
        ["AssistantSizeLarge"] = "Large",
        ["PirateCandidateMenu"] = "Pirate this app!",
        ["DeleteCandidateMenu"] = "Uninstall…",
        ["FilePathCandidateMenu"] = "Open file location",
        ["IgnoredCandidateStatus"] = "{0} added to Pirate Lover!",
        ["SystemUninstallerOpened"] = "System uninstall page opened.",
        ["FilePathMissing"] = "File path not found.",
        ["AppOpenStatus"] = "{0} is open. Update skipped.",
        ["AppOpenFooter"] = "Close {0} first.",
        ["FailureAttemptStatus"] = "Failed {0}/{1}",
        ["BlockedStatus"] = "Blocked",
        ["BlockedAfterFailuresFooter"] = "{0} failed three times. Blocked for now.",
        ["UpdatedUnverified"] = "{0} updated. Warning: {1}",
        ["TrustUnsigned"] = "installer is not signed",
        ["TrustInvalidSig"] = "signature could not be verified",
        ["TrustPublisherMismatch"] = "signed by '{0}', not the expected '{1}'",
        ["ChecksumMismatch"] = "{0} checksum did not match; the download may be corrupted",
        ["InstallerTooLarge"] = "Installer is unexpectedly large; stopped",
        ["UnsafeDownloadPath"] = "Download path escaped Sweepable’r’s folder; stopped",
        ["AppOpenAskClose"] = "I can't update {0} because it's open in the background. Would you like to close it?",
        ["ClosingApp"] = "Closing {0}...",
        ["AppCloseFailed"] = "Couldn't close {0}; update skipped.",
        ["DesktopShortcutsCleaned"] = "Sweep finished. Removed {0} new desktop shortcut(s).",
        ["ResetBlocksMenu"] = "Reset blocked updates",
        ["BlocksReset"] = "{0} block(s) reset.",
        ["SetupPreparing"] = "Getting your PC ready",
        ["SetupPrepareExplanation"] = "Required tools are installed and refreshed. Sweepable’r opens automatically.",
        ["SetupPreparingFolders"] = "Checking local folders and write access...",
        ["SetupReady"] = "Ready to Sweep!",
        ["SetupNoTools"] = "Required tools are missing.",
        ["SetupToolsFound"] = "Installed tools: {0}",
        ["LanguageMenu"] = "Language",
        ["Minimize"] = "Minimize",
        ["DownloadReady"] = "Downloaded; waiting to install",
        ["DownloadQueued"] = "Queued for download",
        ["UsingVerifiedDownload"] = "Using a verified download",
        ["DownloadIncomplete"] = "Download is incomplete; installer was not run.",
        ["SetupCheckingTool"] = "Checking {0}...",
        ["SetupInstallingTool"] = "Installing {0}...",
        ["SetupToolFailed"] = "Could not prepare {0}. Please retry.",
        ["SetupStillPreparing"] = "Tool installation is still running...",
        ["SetupToolError"] = "Tool installation failed.",
        ["SetupNeedsRepair"] = "Setup needs attention",
        ["SetupRetry"] = "Retry setup",
        ["UnsafeLinkedPath"] = "A linked data path was rejected.",
        ["SelfSweepButton"] = "Sweep the Sweepable’r",
        ["DeleteSelfButton"] = "Delete Sweepable’r",
        ["SelfChecking"] = "Checking Sweepable’r...",
        ["SelfCurrent"] = "Sweepable’r is up to date!",
        ["SelfUnverified"] = "The new Sweepable’r release could not be verified.",
        ["SelfPortableOnly"] = "This action requires the portable EXE build.",
        ["SelfRestarting"] = "Updating and restarting Sweepable’r...",
        ["DeleteSelfConfirm"] = "Delete this copy of Sweepable’r? The app will close and remove only {0}."
    };

    private readonly IReadOnlyDictionary<string, string> _strings;

    public static LocalizationService Current { get; private set; } = new("tr");

    public LocalizationService(string language)
    {
        Language = string.Equals(language, "en", StringComparison.OrdinalIgnoreCase)
            ? "en"
            : "tr";
        _strings = Language == "en" ? English : Turkish;
    }

    public string Language { get; }

    public string AppName => Get("AppName");

    public static void SetCurrent(string language)
    {
        Current = new LocalizationService(language);
    }

    public string Get(string key)
    {
        return _strings.TryGetValue(key, out var value)
            ? value
            : Turkish.TryGetValue(key, out var turkish)
                ? turkish
                : key;
    }
}
